### ISSUE TITLE
Support for Logical Negation Symbol Combination

### ISSUE THREAD

**Issue by NanachiKyubey** [kokic/UniTeX#10]
应该考虑支持一些latex符号和否定符号的组合转译到unicode。

输入  >  预期输出

1.  \not, U+0338
- \not\in  >  \notin 
- \not\ni  >  \notni
- \not\exist  >  \noexist
- ...
- [...并且应该支持所有能跟否定斜线组合的字符...](https://www.compart.com/en/unicode/U+0338)

**Comment by kokic** [comment]
Thanks, fix it by https://github.com/kokic/UniTeX/commit/5edc8cf88a2dd2962f9ce1201f01d53319170d9e.
