### ISSUE TITLE
Add Hebrew Support

### ISSUE THREAD

**Issue by NanachiKyubey** [kokic/UniTeX#11]
也不是说想要完整的希伯来语支持
但最为初级最常用的
\aleph \beth \gimel \daleth 
只有\aleph生效，后面仨无效

### 参考

https://tex.stackexchange.com/q/226793

**Comment by kokic** [comment]
done with https://github.com/kokic/UniTeX/commit/2defa049bd351c4d7398108a5827823dc00ab50c.
